<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Central tendency II – TEXTBOOK OF AGRICULTURAL STATISTICS</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./appendix1.html" rel="next">
<link href="./central1.html" rel="prev">
<link href="./images/papayalogo.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ed3264ca69fda7dec8d1e4b54715bc75.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="5&nbsp; Central tendency II – TEXTBOOK OF AGRICULTURAL STATISTICS">
<meta property="og:description" content="">
<meta property="og:image" content="https://cleaning-data-r.ala.org.au/images/cover.jpg">
<meta property="og:site_name" content="TEXTBOOK OF AGRICULTURAL STATISTICS">
<meta property="og:image:alt" content="Textbook of Agricultural Statistics">
<meta name="twitter:title" content="5&nbsp; Central tendency II – TEXTBOOK OF AGRICULTURAL STATISTICS">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://cleaning-data-r.ala.org.au/images/papayalogo.png">
<meta name="twitter:image:alt" content="Textbook of Agricultural Statistics">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="434">
<meta name="twitter:image-width" content="853">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./central2.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Central tendency II</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/papayalogo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">TEXTBOOK OF AGRICULTURAL STATISTICS</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/AtlasOfLivingAustralia/cleaning_data" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Basics of statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./agstatindia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Statistics on agriculture</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3graph.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Graphical representation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./central1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Central tendency I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./central2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Central tendency II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Appendix 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#geometric-mean" id="toc-geometric-mean" class="nav-link active" data-scroll-target="#geometric-mean"><span class="header-section-number">5.1</span> Geometric mean</a>
  <ul class="collapse">
  <li><a href="#geometric-mean-for-grouped-frequency-table-data" id="toc-geometric-mean-for-grouped-frequency-table-data" class="nav-link" data-scroll-target="#geometric-mean-for-grouped-frequency-table-data"><span class="header-section-number">5.1.1</span> Geometric mean for grouped frequency table data</a></li>
  </ul></li>
  <li><a href="#harmonic-mean" id="toc-harmonic-mean" class="nav-link" data-scroll-target="#harmonic-mean"><span class="header-section-number">5.2</span> Harmonic mean</a></li>
  <li><a href="#relation-between-am-gm-and-hm" id="toc-relation-between-am-gm-and-hm" class="nav-link" data-scroll-target="#relation-between-am-gm-and-hm"><span class="header-section-number">5.3</span> Relation between AM, GM and HM</a></li>
  <li><a href="#am-gm-or-hm" id="toc-am-gm-or-hm" class="nav-link" data-scroll-target="#am-gm-or-hm"><span class="header-section-number">5.4</span> AM, GM or HM ?</a></li>
  <li><a href="#sec-positional_avg" id="toc-sec-positional_avg" class="nav-link" data-scroll-target="#sec-positional_avg"><span class="header-section-number">5.5</span> Positional Averages</a></li>
  <li><a href="#quartile" id="toc-quartile" class="nav-link" data-scroll-target="#quartile"><span class="header-section-number">5.6</span> Quartiles</a>
  <ul class="collapse">
  <li><a href="#quartiles-of-a-discrete-frequency-data" id="toc-quartiles-of-a-discrete-frequency-data" class="nav-link" data-scroll-target="#quartiles-of-a-discrete-frequency-data"><span class="header-section-number">5.6.1</span> Quartiles of a discrete frequency data</a></li>
  <li><a href="#quartiles-of-a-continuous-frequency-data" id="toc-quartiles-of-a-continuous-frequency-data" class="nav-link" data-scroll-target="#quartiles-of-a-continuous-frequency-data"><span class="header-section-number">5.6.2</span> Quartiles of a continuous frequency data</a></li>
  </ul></li>
  <li><a href="#percentiles" id="toc-percentiles" class="nav-link" data-scroll-target="#percentiles"><span class="header-section-number">5.7</span> Percentiles</a></li>
  <li><a href="#deciles" id="toc-deciles" class="nav-link" data-scroll-target="#deciles"><span class="header-section-number">5.8</span> Deciles</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Central tendency II</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>While simple averages like mean, median, and mode are widely used to summarize data, certain situations call for more specialized measures to capture the essence of a dataset. <strong>Special averages</strong>, including the <strong>geometric mean</strong> and <strong>harmonic mean</strong>, are tailored for specific contexts where the nature of the data or the relationships between data points require a different approach.</p>
<section id="geometric-mean" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="geometric-mean"><span class="header-section-number">5.1</span> Geometric mean</h2>
<p>The <strong>geometric mean</strong> is a specialized measure of central tendency, particularly suited for datasets involving growth rates, ratios, or percentages, such as population growth, investment returns, or interest rates. Unlike the arithmetic mean, which calculates the average by summing values, the geometric mean finds the average by multiplying values and then taking the root (typically the n<sup>th</sup> root for n values).</p>
<p>This approach captures the compounding effects present in the data, making the geometric mean an essential tool for accurately summarizing proportional changes or rates over time. Its utility lies in providing a more representative measure for datasets where changes are multiplicative rather than additive.</p>
<p>The geometric mean of a series containing <em>n</em> observations is the <em>n</em><sup>th</sup> root of the product of the values. If <span class="math inline">\(x_{1},x_{2},\ldots,&nbsp;x_{n}\)</span>are observations then</p>
<p><span class="math display">\[\mathbf{\text{Geometric mean}}\mathbf{,\ }\mathbf{GM =}\sqrt[\mathbf{n}]{\mathbf{x}_{\mathbf{1}}\mathbf{x}_{\mathbf{2}}\mathbf{\ldots}\mathbf{x}_{\mathbf{n}}}\]</span></p>
<p><span class="math display">\[\mathbf{=}\left( \mathbf{x}_{\mathbf{1}}\mathbf{x}_{\mathbf{2}}\mathbf{\ldots}\mathbf{x}_{\mathbf{n}} \right)^{\frac{\mathbf{1}}{\mathbf{n}}}\]</span></p>
<p><span class="math display">\[\mathbf{\log}\mathbf{\text{GM}}\mathbf{=}\frac{\mathbf{1}}{\mathbf{n}}\mathbf{\log}\left( \mathbf{x}_{\mathbf{1}}\mathbf{x}_{\mathbf{2}}\mathbf{\ldots}\mathbf{x}_{\mathbf{n}} \right)\]</span></p>
<p><span class="math display">\[\mathbf{=}\frac{\mathbf{1}}{\mathbf{n}}\left( \mathbf{\log}\mathbf{x}_{\mathbf{1}}\mathbf{+}\mathbf{\log}\mathbf{x}_{\mathbf{2}}\mathbf{\ldots +}\mathbf{\log}\mathbf{x}_{\mathbf{n}} \right)\]</span></p>
<p><span class="math display">\[\mathbf{=}\frac{\sum_{\mathbf{i = 1}}^{\mathbf{n}}{\mathbf{\log}\mathbf{x}_{\mathbf{i}}}}{\mathbf{n}}\]</span></p>
<p><span class="math display">\[\mathbf{\ GM = Antilog}\left( \frac{\sum_{\mathbf{i = 1}}^{\mathbf{n}}{\mathbf{\log}\mathbf{x}_{\mathbf{i}}}}{\mathbf{n}} \right)\]</span></p>
<section id="geometric-mean-for-grouped-frequency-table-data" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="geometric-mean-for-grouped-frequency-table-data"><span class="header-section-number">5.1.1</span> Geometric mean for grouped frequency table data</h3>
<p><span class="math display">\[\mathbf{GM = \ Antilog}\left( \frac{\sum_{\mathbf{i = 1}}^{\mathbf{k}}{{\mathbf{f}_{\mathbf{i}}\mathbf{\log}}\mathbf{x}_{\mathbf{i}}}}{\mathbf{n}} \right)\]</span></p>
<p>where <span class="math inline">\(x_{i}\)</span> is the mid-value, <span class="math inline">\(f_{i}\)</span> is the frequency , <em>k</em> is the number of classes</p>
<p><strong>Example 5.1</strong>: If the weight of sorghum ear heads are 45, 60, 48,100, 65 gms. Find the Geometric mean?</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Weight of ear head (x)</th>
<th style="text-align: center;">log(x)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">45</td>
<td style="text-align: center;">1.653</td>
</tr>
<tr class="even">
<td style="text-align: center;">60</td>
<td style="text-align: center;">1.778</td>
</tr>
<tr class="odd">
<td style="text-align: center;">48</td>
<td style="text-align: center;">1.681</td>
</tr>
<tr class="even">
<td style="text-align: center;">100</td>
<td style="text-align: center;">2.000</td>
</tr>
<tr class="odd">
<td style="text-align: center;">65</td>
<td style="text-align: center;">1.813</td>
</tr>
<tr class="even">
<td style="text-align: center;">Total</td>
<td style="text-align: center;"><strong>8.926</strong></td>
</tr>
</tbody>
</table>
<p><strong>Solution 5.1</strong>:</p>
<p>Here <em>n</em> =5</p>
<p>Geometric mean=<br>
<span class="math display">\[\text{Antilog}\left( \frac{\sum_{i = 1}^{n}{\log x_{i}}}{n} \right) \]</span><br>
<span class="math display">\[=\text{Antilog}\left( \frac{8.926}{5} \right) \]</span><br>
<span class="math display">\[ =\text{Antilog}(1.785) = 60.95\]</span> note: here <span class="math inline">\(\text{Antilog}\left( x \right) = 10^{x}\)</span> <em>i</em>.<em>e</em>. <span class="math display">\[\text{Antilog}\left( 1.785 \right) = \ 10^{1.785} = 60.95\]</span></p>
<p><strong>Example 5.2</strong>: Geometric mean of a Frequency Distribution</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Weight of ear head (<em>x</em>)</th>
<th style="text-align: center;">Frequency(<em>f</em>)</th>
<th style="text-align: center;">log(<em>x</em>)</th>
<th style="text-align: center;">flog(<em>x</em>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">45</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">1.653</td>
<td style="text-align: center;">8.266</td>
</tr>
<tr class="even">
<td style="text-align: center;">60</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">1.778</td>
<td style="text-align: center;">7.113</td>
</tr>
<tr class="odd">
<td style="text-align: center;">48</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">1.681</td>
<td style="text-align: center;">10.087</td>
</tr>
<tr class="even">
<td style="text-align: center;">100</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">2.000</td>
<td style="text-align: center;">16.000</td>
</tr>
<tr class="odd">
<td style="text-align: center;">65</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">1.813</td>
<td style="text-align: center;">16.316</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Total</strong></td>
<td style="text-align: center;"><strong>32</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>57.782</strong></td>
</tr>
</tbody>
</table>
<p><strong>Solution 5.2</strong>: Here <em>n</em> =32</p>
<p><span class="math display">\[GM = \ Antilog\left( \frac{\sum_{i = 1}^{k}{{f_{i}\log}x_{i}}}{n} \right)\]</span></p>
<p><span class="math display">\[{\sum_{i = 1}^{k}{{f_{i}\log}x_{i}} = 57.782
}\]</span><br>
<span class="math display">\[{\text{GM} = \ Antilog\left( \frac{57.782}{32} \right)  }\]</span><br>
<span class="math display">\[{= Antilog\left( 1.8056 \right)= 10^{1.8056} = 63.92}\]</span> <strong>Example 5.3</strong>: Geometric mean of a Grouped Frequency Distribution</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Class</th>
<th style="text-align: center;">Mid value (<em>x</em>)</th>
<th style="text-align: center;">Frequency(<em>f</em>)</th>
<th style="text-align: center;">log(<em>x</em>)</th>
<th style="text-align: center;">flog(x)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">60-80</td>
<td style="text-align: center;">70</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">1.845</td>
<td style="text-align: center;">9.225</td>
</tr>
<tr class="even">
<td style="text-align: center;">80-100</td>
<td style="text-align: center;">90</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">1.954</td>
<td style="text-align: center;">7.817</td>
</tr>
<tr class="odd">
<td style="text-align: center;">100-120</td>
<td style="text-align: center;">110</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">2.041</td>
<td style="text-align: center;">12.248</td>
</tr>
<tr class="even">
<td style="text-align: center;">120-140</td>
<td style="text-align: center;">130</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">2.114</td>
<td style="text-align: center;">16.912</td>
</tr>
<tr class="odd">
<td style="text-align: center;">140-160</td>
<td style="text-align: center;">150</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">2.176</td>
<td style="text-align: center;">19.585</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>Total</strong></td>
<td style="text-align: center;"><strong>32</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>65.787</strong></td>
</tr>
</tbody>
</table>
<p><strong>Solution 5.4</strong>:<br>
Here <em>n</em> =32</p>
<p><span class="math display">\[GM = \ Antilog\left( \frac{\sum_{i = 1}^{k}{{f_{i}\log}x_{i}}}{n} \right)\]</span></p>
<p><span class="math display">\[{\sum_{i = 1}^{k}{{f_{i}\log}x_{i}} = 65.787}\]</span> <span class="math display">\[{\text{GM} = \ Antilog\left( \frac{65.787}{32} \right)}\]</span> <span class="math display">\[{= Antilog\left( 2.0558 \right) = 10^{2.0558} = 113.71}\]</span></p>
<p><strong>Merits and Demerits of Geometric mean</strong></p>
<p><span class="ui"><strong>Merits</strong></span></p>
<ul>
<li><p>It is rigidly defined.</p></li>
<li><p>It is based on all the observations of the series.</p></li>
<li><p>It is suitable for measuring the relative changes.</p></li>
<li><p>It gives more weights to the small values and less weight to the large values.</p></li>
<li><p>It is used in averaging the ratios, percentages and in determining the rate gradual increase and decrease.</p></li>
<li><p>It is capable of further algebraic treatment.</p></li>
</ul>
<p><span class="ui"><strong>Demerits</strong></span></p>
<ul>
<li><p>It is not easy to understand.</p></li>
<li><p>It is difficult to calculate.</p></li>
<li><p>It cannot be calculated, if the number of negative values is odd.</p></li>
<li><p>It cannot be calculated, if any value of a series is zero.</p></li>
<li><p>At times it gives a value which may not be found in the series or impractical.</p></li>
</ul>
</section>
</section>
<section id="harmonic-mean" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="harmonic-mean"><span class="header-section-number">5.2</span> Harmonic mean</h2>
<p>Harmonic means are often used in averaging things like rates (e.g.&nbsp;the average travel speed given duration of several trips). Harmonic mean (HM) of a set of observations is defined as the reciprocal of the arithmetic average of the reciprocal of the given value.</p>
<p>If <span class="math inline">\(x_{1},\ x_{2},\ldots,\ x_{n}\)</span> are <em>n</em> observations then</p>
<p><span class="math display">\[\mathbf{\text{H.M}} = \frac{n}{\sum_{i = 1}^{n}\frac{1}{x_{i}}}\]</span></p>
<p><u>In case of Frequency distribution</u></p>
<p><span class="math display">\[\mathbf{\text{H.M}} = \frac{n}{\sum_{i = 1}^{k}{f_{i}\frac{1}{x_{i}}}}\]</span></p>
<p>where <span class="math inline">\(x_{i}\)</span> is the mid-value, <span class="math inline">\(f_{i}\)</span> is the frequency , <em>k</em> is the number of classes</p>
<p><u><strong>Steps in calculating Harmonic Mean (H.M)</strong></u></p>
<ol type="1">
<li><p>Calculate the reciprocal (1/value) for every value.</p></li>
<li><p>Find the average of those reciprocals (just add them and divide by how many there are)</p></li>
<li><p>Then do the reciprocal of that average (=1/average)</p></li>
</ol>
<p><strong>Example 5.4</strong>: From the given data 5, 10, 17, 24, 30 calculate H.M</p>
<p><strong>Solution 5.4</strong>:</p>
<p>Here <em>n</em> = 5</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">x</th>
<th style="text-align: center;">1/x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">0.2</td>
</tr>
<tr class="even">
<td style="text-align: center;">10</td>
<td style="text-align: center;">0.1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">17</td>
<td style="text-align: center;">0.059</td>
</tr>
<tr class="even">
<td style="text-align: center;">24</td>
<td style="text-align: center;">0.042</td>
</tr>
<tr class="odd">
<td style="text-align: center;">30</td>
<td style="text-align: center;">0.033</td>
</tr>
<tr class="even">
<td style="text-align: center;">Total</td>
<td style="text-align: center;"><strong>0.434</strong></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\mathbf{\text{H.M}} = \frac{n}{\sum_{i = 1}^{n}\frac{1}{x_{i}}} = \frac{5}{0.433824} = 11.525\]</span></p>
<p><strong>Example 5.5</strong>: Number of tomatoes per plant are given below. Calculate the harmonic mean.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">No.&nbsp;of Tomato per plants</th>
<th style="text-align: left;">20</th>
<th style="text-align: left;">21</th>
<th style="text-align: left;">22</th>
<th style="text-align: left;">23</th>
<th style="text-align: left;">24</th>
<th style="text-align: left;">25</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No.&nbsp;of Plants</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">1</td>
</tr>
</tbody>
</table>
<p><strong>Solution 5.5</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">x</th>
<th style="text-align: center;">f</th>
<th style="text-align: center;">1/x</th>
<th style="text-align: center;">f(1/x)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">20</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0.050</td>
<td style="text-align: center;">0.200</td>
</tr>
<tr class="even">
<td style="text-align: left;">21</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.048</td>
<td style="text-align: center;">0.095</td>
</tr>
<tr class="odd">
<td style="text-align: left;">22</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">0.045</td>
<td style="text-align: center;">0.318</td>
</tr>
<tr class="even">
<td style="text-align: left;">23</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.043</td>
<td style="text-align: center;">0.043</td>
</tr>
<tr class="odd">
<td style="text-align: left;">24</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.042</td>
<td style="text-align: center;">0.125</td>
</tr>
<tr class="even">
<td style="text-align: left;">25</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.040</td>
<td style="text-align: center;">0.04</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;"><strong>18</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>0.822</strong></td>
</tr>
</tbody>
</table>
<p>Here <em>n</em> =18</p>
<p><span class="math display">\[\mathbf{\text{H.M}} = \frac{n}{\sum_{i = 1}^{n}{f_{i}\frac{1}{x_{i}}}} = \frac{18}{0.821898} = 21.90\]</span></p>
<p><strong>Merits and Demerits of Harmonic mean</strong></p>
<p><u><strong>Merits</strong></u></p>
<ul>
<li><p>It is rigidly defined.</p></li>
<li><p>It is defined on all observations.</p></li>
<li><p>It is amenable to further algebraic treatment.</p></li>
<li><p>It is the most suitable average when it is desired to give greater weight to smaller and less weight to the larger ones.</p></li>
</ul>
<p><u><strong>Demerits</strong></u></p>
<ul>
<li><p>It is not easily understood.</p></li>
<li><p>It is difficult to compute.</p></li>
<li><p>It is only a summary figure and may not be the actual item in the series.</p></li>
<li><p>It gives greater importance to small items and is therefore, useful only when small items have to be given greater weightage.</p></li>
<li><p>It is rarely used in grouped data.</p></li>
</ul>
</section>
<section id="relation-between-am-gm-and-hm" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="relation-between-am-gm-and-hm"><span class="header-section-number">5.3</span> Relation between AM, GM and HM</h2>
<p>If AM stands for Arithmetic Mean, GM stands for Geometric Mean and HM stands for Harmonic Mean; then</p>
<p><span class="math display">\[\mathbf{\text{AM}}\mathbf{\times}\mathbf{\text{HM}}\mathbf{=}\mathbf{\text{GM}}^{\mathbf{2}}\]</span></p>
<p>also</p>
<p><span class="math display">\[\mathbf{AM \geq GM \geq HM}\]</span></p>
</section>
<section id="am-gm-or-hm" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="am-gm-or-hm"><span class="header-section-number">5.4</span> AM, GM or HM ?</h2>
<p>Choosing the right average depends on what you’re measuring and how the data behaves. Let’s break it down step by step in a simple way:</p>
<p><strong>Arithmetic Mean (AM)</strong><br>
The arithmetic mean is the most common type of average. You use it when the values in your data add together in a straightforward way. This is suitable for quantities like:<br>
- Heights or weights<br>
- Lengths or distances<br>
- Marks in exams</p>
<p>For example, if you want to find the average height of students in a class, you add up all the heights and divide by the number of students. The arithmetic mean gives a meaningful average because height or weight adds linearly—it’s a direct measurement.</p>
<p><strong>Harmonic Mean (HM)</strong><br>
The harmonic mean is useful when you are working with rates, ratios, or situations where quantities add up as <strong>reciprocals</strong>. Some examples include:<br>
- Speeds (distance per unit time)<br>
- Capacitors in a series circuit<br>
- Rates like fuel efficiency or cost per unit</p>
<p>For instance, imagine you are driving the same distance at different speeds. If you want to find the average speed for the entire trip, the harmonic mean is the best choice. This is because speeds relate inversely to time—when you go faster, you take less time, and vice versa.</p>
<p><strong>Geometric Mean (GM)</strong><br>
The geometric mean is the right choice when your data involves multiplication or compounding, such as:<br>
- Growth rates (like population growth or interest rates)<br>
- Percentages (like inflation rates)<br>
- Ratios</p>
<p>For example, if you have annual interest rates for 10 years and want to find a single rate that represents the same total growth over that period, the geometric mean gives you the answer. It works by multiplying the rates and taking the root, which accounts for the compounding effect.</p>
<p><strong>Key Takeaways</strong><br>
1. Use <strong>Arithmetic Mean</strong> when values combine directly, like adding lengths or weights.<br>
2. Use <strong>Harmonic Mean</strong> for rates or quantities that work reciprocally, like speed or resistance.<br>
3. Use <strong>Geometric Mean</strong> for data involving multiplication or compounding, like growth rates or percentages.</p>
<p>By understanding the relationship between the data and the type of average, you can choose the most meaningful measure for your analysis.</p>
</section>
<section id="sec-positional_avg" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="sec-positional_avg"><span class="header-section-number">5.5</span> Positional Averages</h2>
<p>Positional averages are measures derived directly from the values in a dataset. These averages are based on the position of the values within the series and are used to represent the overall dataset or highlight specific positional characteristics.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>median</strong> although a simple average is also a positional average that represents the middle value of an ordered dataset, making it a central point of reference. Similarly, the <strong>mode</strong>, which identifies the most frequently occurring value in the dataset, is also a positional average since it is directly taken from the series.</p>
</div>
</div>
<p>The other common positional averages include <strong>percentiles</strong>, <strong>quartiles</strong>, and <strong>deciles</strong>, which divide the data into equal parts to analyze its distribution.</p>
<p>In contrast, measures like the <strong>arithmetic mean</strong>, <strong>geometric mean</strong>, and <strong>harmonic mean</strong> are referred to as <strong>mathematical averages</strong>, as they are calculated through specific mathematical operations rather than being derived from the data’s positional properties.</p>
</section>
<section id="quartile" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="quartile"><span class="header-section-number">5.6</span> Quartiles</h2>
<p>The <strong>median</strong> divides a dataset into two equal halves. Similarly, it is possible to divide a dataset into more than two parts. When an <strong>ordered</strong> dataset is divided into four equal sections, the points that mark these divisions are called <strong>quartiles</strong>.</p>
<p>The <strong>first or lower quartile (</strong><span class="math inline">\(\mathbf{Q}_{\mathbf{1}}\)</span><strong>)</strong> is a value that has one fourth, or 25% of the observations below its value.</p>
<p>The <strong>second quartile (</strong><span class="math inline">\(\mathbf{Q}_{\mathbf{2}}\)</span><strong>)</strong>, has one-half, or 50% of the observations below its value. The second quartile is equal to the <strong>median</strong>.</p>
<p>The <strong>third or upper quartile</strong>, <strong>(</strong><span class="math inline">\(\mathbf{Q}_{\mathbf{3}}\)</span><strong>)</strong>, is a value that has three-fourths, or 75% of the observations below it.</p>
<p><span class="math inline">\(\mathbf{Q}_{\mathbf{1}}\mathbf{=}\left( \frac{\mathbf{n + 1}}{\mathbf{4}} \right)^{\mathbf{\text{th}}}\)</span><strong>item</strong></p>
<p><span class="math inline">\(\mathbf{Q}_{\mathbf{3}}\mathbf{=}\left( \frac{\mathbf{3(n + 1)}}{\mathbf{4}} \right)^{\mathbf{\text{th}}}\)</span><strong>item</strong></p>
<p>Calculations of quartiles are explained using the example below. See in the example the procedure followed when a fraction appear in the calculation.</p>
<p><strong>Example 5.6</strong>: Compute quartiles for the data 25, 18, 30, 8, 15, 5, 10, 35, 40, 45</p>
<p><strong>Solution 5.6</strong>:</p>
<p>First arrange the data in ascending order</p>
<p><strong>5, 8, 10, 15, 18, 25, 30, 35, 40, 45</strong></p>
<p>here <em>n</em> = 10</p>
<p><span class="math inline">\(\mathbf{Q}_{\mathbf{1}}\mathbf{=}\left(\frac{\mathbf{n + 1}}{\mathbf{4}} \right)^{\mathbf{\text{th}}}\)</span><strong>item</strong></p>
<p><em>i</em>.<em>e</em>. <span class="math inline">\(Q_{1} = \left( \frac{10 + 1}{4} \right)^{th}\)</span> = 2.75<sup>th</sup> item; when such a fraction appears we use the following procedure</p>
<p><span class="math inline">\(Q_{1} =\)</span><!-- -->2.75<sup>th</sup> item = 2<sup>nd</sup> item + 0.75(3<sup>rd</sup> item – 2<sup>nd</sup> item)</p>
<p>So from the given data <span class="math inline">\(Q_{1}\)</span>= 8+0.75(10– 8) = <strong>9.5</strong></p>
<p><span class="math display">\[\mathbf{Q}_{\mathbf{2}}\mathbf{= median}\]</span></p>
<p>here <span class="math inline">\(Q_{2} =\)</span>(18+25)/2 = <strong>21.5</strong></p>
<p><span class="math inline">\(\mathbf{Q}_{\mathbf{3}}\mathbf{=}\left( \frac{\mathbf{3(n + 1)}}{\mathbf{4}} \right)^{\mathbf{\text{th}}}\)</span><strong>item</strong></p>
<p><em>i</em>.<em>e</em>. <span class="math inline">\(Q_{3} = \left( 3 \times \frac{(10 + 1)}{4} \right)^{th}\)</span> = 8.25<sup>th</sup> item = 8<sup>th</sup> item + 0.25(9<sup>th</sup> item –8<sup>th</sup> item) = 35+0.25(40-35) =<strong>36.25</strong></p>
<section id="quartiles-of-a-discrete-frequency-data" class="level3" data-number="5.6.1">
<h3 data-number="5.6.1" class="anchored" data-anchor-id="quartiles-of-a-discrete-frequency-data"><span class="header-section-number">5.6.1</span> Quartiles of a discrete frequency data</h3>
<ol type="1">
<li><p>Find cumulative frequencies.</p></li>
<li><p>Find <span class="math inline">\(\left( \frac{\mathbf{n + 1}}{\mathbf{4}} \right)\)</span></p></li>
<li><p>See in the cumulative frequencies, the value just greater than <span class="math inline">\(\left( \frac{\mathbf{n + 1}}{\mathbf{4}} \right)\)</span> , then the corresponding value of <span class="math inline">\(x\)</span> is <span class="math inline">\(Q_{1}\)</span></p></li>
<li><p>Find <span class="math inline">\(\left( \frac{\mathbf{3(n + 1)}}{\mathbf{4}} \right)\)</span></p></li>
<li><p>See in the cumulative frequencies, the value just greater than <span class="math inline">\(\left( \frac{\mathbf{3(n + 1)}}{\mathbf{4}} \right)\)</span> ,then the corresponding value of <span class="math inline">\(x\)</span> is <span class="math inline">\(Q_{3}\)</span></p></li>
</ol>
<p><strong>Example 5.7</strong>: Compute quartiles for the data given bellow</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(\mathbf{x}\)</span></th>
<th style="text-align: center;">5</th>
<th style="text-align: center;">8</th>
<th style="text-align: center;">12</th>
<th style="text-align: center;">15</th>
<th style="text-align: center;">19</th>
<th style="text-align: center;">24</th>
<th style="text-align: center;">30</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\mathbf{f}\)</span></td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
</tr>
</tbody>
</table>
<p><strong>Solution 5.7</strong>:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">x</th>
<th style="text-align: center;">f</th>
<th style="text-align: center;">cf</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="odd">
<td style="text-align: center;">12</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="even">
<td style="text-align: center;">15</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">13</td>
</tr>
<tr class="odd">
<td style="text-align: center;">19</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">18</td>
</tr>
<tr class="even">
<td style="text-align: center;">24</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">20</td>
</tr>
<tr class="odd">
<td style="text-align: center;">30</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">24</td>
</tr>
</tbody>
</table>
<p>Here <em>n</em> =24</p>
<p><span class="math inline">\(\left( \frac{\mathbf{n + 1}}{\mathbf{4}} \right)\)</span> <strong>=</strong> <span class="math inline">\(\left( \frac{\mathbf{n + 1}}{\mathbf{4}} \right)\mathbf{\ }\)</span><strong>=</strong> <span class="math inline">\(\left( \frac{\mathbf{25}}{\mathbf{4}} \right)\)</span><strong>=</strong> 6.25</p>
<p>The cumulative frequency value just greater than 6.25 is 7, the<br>
<span class="math inline">\(\mathbf{x}\)</span> value corresponding to cumulative frequency 7 is 8. So <span class="math inline">\(\mathbf{Q}_{\mathbf{1}}\)</span><strong>= 8</strong></p>
<p><span class="math inline">\(\left( \frac{\mathbf{3(n + 1)}}{\mathbf{4}} \right)\)</span> <strong>=</strong> <span class="math inline">\(\left( \frac{\mathbf{3}\mathbf{\times}\mathbf{25}}{\mathbf{4}} \right)\)</span><strong>=</strong> 18.75</p>
<p>The cumulative frequency value just greater than 18.75 is 20, the<br>
<span class="math inline">\(\mathbf{x}\)</span> value corresponding to cumulative frequency 20 is 24. So <span class="math inline">\(\mathbf{Q}_{\mathbf{3}}\)</span><strong>= 24</strong></p>
</section>
<section id="quartiles-of-a-continuous-frequency-data" class="level3" data-number="5.6.2">
<h3 data-number="5.6.2" class="anchored" data-anchor-id="quartiles-of-a-continuous-frequency-data"><span class="header-section-number">5.6.2</span> Quartiles of a continuous frequency data</h3>
<ol type="1">
<li><p>Find cumulative frequencies</p></li>
<li><p>Find <span class="math inline">\(\left( \frac{\mathbf{n}}{\mathbf{4}} \right)\)</span></p></li>
<li><p>See in the cumulative frequencies, the value just greater than<span class="math inline">\(\ \left( \frac{\mathbf{n}}{\mathbf{4}} \right)\)</span>, and then the corresponding class interval is called <strong>first quartile class</strong>.</p></li>
<li><p>Find <span class="math inline">\(3\left( \frac{\mathbf{n}}{\mathbf{4}} \right)\)</span></p></li>
<li><p>See in the cumulative frequencies the value just greater than <span class="math inline">\(3\left( \frac{\mathbf{n}}{\mathbf{4}} \right)\mathbf{\ }\)</span>then the corresponding class interval is called <strong>3<sup>rd</sup> quartile class</strong>. Then apply the respective formulae</p></li>
</ol>
<p><span class="math display">\[\mathbf{Q}_{\mathbf{1}}\mathbf{=}\mathbf{l}_{\mathbf{1}}\mathbf{+}\frac{\frac{\mathbf{n}}{\mathbf{4}}\mathbf{-}\mathbf{m}_{\mathbf{1}}}{\mathbf{f}_{\mathbf{1}}}\mathbf{\times}\mathbf{c}_{\mathbf{1}}\]</span></p>
<p><span class="math display">\[\mathbf{Q}_{\mathbf{3}}\mathbf{=}\mathbf{l}_{\mathbf{3}}\mathbf{+}\frac{\mathbf{3}\left( \frac{\mathbf{n}}{\mathbf{4}} \right)\mathbf{-}\mathbf{m}_{\mathbf{3}}}{\mathbf{f}_{\mathbf{3}}}\mathbf{\times}\mathbf{c}_{\mathbf{3}}\]</span></p>
<p>Where, <span class="math inline">\(l_{1}\)</span> = lower limit of the first quartile class</p>
<p><span class="math inline">\(f_{1}\)</span> = frequency of the first quartile class</p>
<p><span class="math inline">\(c_{1}\)</span> = width of the first quartile class</p>
<p><span class="math inline">\(m_{1}\)</span> = cumulative frequency preceding the first quartile class</p>
<p><span class="math inline">\(l_{3}\)</span>= 1ower limit of the 3<sup>rd</sup> quartile class</p>
<p><span class="math inline">\(f_{3}\)</span>= frequency of the 3<sup>rd</sup> quartile class</p>
<p><span class="math inline">\(c_{3}\)</span>= width of the 3<sup>rd</sup> quartile class</p>
<p><span class="math inline">\(m_{3}\)</span> = cumulative frequency preceding the 3<sup>rd</sup> quartile class</p>
<p><strong>Example 5.8</strong>: Find the quartiles for the grouped frequency data given</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Class</strong></th>
<th style="text-align: center;"><strong>frequency</strong></th>
<th style="text-align: center;"><strong>cumulative frequency</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0-10</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="even">
<td style="text-align: center;">10-20</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">29</td>
</tr>
<tr class="odd">
<td style="text-align: center;">20-30</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">54</td>
</tr>
<tr class="even">
<td style="text-align: center;">30-40</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">82</td>
</tr>
<tr class="odd">
<td style="text-align: center;">40-50</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">112</td>
</tr>
<tr class="even">
<td style="text-align: center;">50-60</td>
<td style="text-align: center;">33</td>
<td style="text-align: center;">145</td>
</tr>
<tr class="odd">
<td style="text-align: center;">60-70</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">167</td>
</tr>
<tr class="even">
<td style="text-align: center;">70-80</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">182</td>
</tr>
<tr class="odd">
<td style="text-align: center;">80-90</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">194</td>
</tr>
<tr class="even">
<td style="text-align: center;">90-100</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">204</td>
</tr>
</tbody>
</table>
<p><strong>Solution 5.8</strong>:</p>
<p><span class="math inline">\(\left( \frac{n}{4} \right)\)</span> = <span class="math inline">\(\frac{204}{4}\)</span> = 51</p>
<p>The cumulative frequency value just greater than 51 is 54 so the class 20-30 is the 1<sup>st</sup> quartile class</p>
<p><span class="math display">\[\mathbf{Q}_{\mathbf{1}}\mathbf{=}\mathbf{l}_{\mathbf{1}}\mathbf{+}\frac{\frac{\mathbf{n}}{\mathbf{4}}\mathbf{-}\mathbf{m}_{\mathbf{1}}}{\mathbf{f}_{\mathbf{1}}}\mathbf{\times}\mathbf{c}_{\mathbf{1}}\]</span></p>
<p><span class="math display">\[\mathbf{= 20 +}\frac{\mathbf{51 - 29}}{\mathbf{25}}\mathbf{\times 10\  = 28.8}\]</span></p>
<p><span class="math inline">\(3\left( \frac{n}{4} \right)\)</span>= <span class="math inline">\(3 \times \frac{204}{4}\)</span> = 153</p>
<p>The cumulative frequency value just greater than 153 is 167 so the class 60-70 is the 3<sup>rd</sup> quartile class</p>
<p><span class="math display">\[\mathbf{Q}_{\mathbf{3}}\mathbf{=}\mathbf{l}_{\mathbf{3}}\mathbf{+}\frac{\mathbf{3}\left( \frac{\mathbf{n}}{\mathbf{4}} \right)\mathbf{-}\mathbf{m}_{\mathbf{3}}}{\mathbf{f}_{\mathbf{3}}}\mathbf{\times}\mathbf{c}_{\mathbf{3}}\]</span></p>
<p><span class="math display">\[\mathbf{= 60 +}\frac{\mathbf{153 - 145}}{\mathbf{22}}\mathbf{\times 10 = 63.63}\]</span></p>
</section>
</section>
<section id="percentiles" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="percentiles"><span class="header-section-number">5.7</span> Percentiles</h2>
<p>Percentiles divide an <strong>ordered dataset</strong> into 100 equal parts, with each part containing 1% of the observations. The <strong>x</strong><sup>th</sup> percentile, denoted as <span class="math inline">\(P_x\)</span>, is the value below which <strong>x</strong> percent of the data falls.</p>
<p>For example:<br>
- The <strong>50th percentile</strong> is equivalent to the <strong>median</strong>, representing the middle value of the dataset.<br>
- The <strong>25th percentile</strong> corresponds to the first quartile (<span class="math inline">\(Q_1\)</span>), which marks the lower 25% of the data.<br>
- The <strong>75th percentile</strong> is the third quartile (<span class="math inline">\(Q_3\)</span>), indicating that 75% of the data falls below this value.</p>
<p>For raw data, first arrange the <em>n</em> observations in increasing order. Then the <em>x</em><sup>th</sup> percentile is given by</p>
<p><span class="math inline">\(\mathbf{P}_{\mathbf{x}}\mathbf{=}\left( \frac{\mathbf{x}\left( \mathbf{n + 1} \right)}{\mathbf{100}} \right)^{\mathbf{\text{th}}}\)</span><strong>item</strong></p>
<p>For a frequency distribution the <em>x</em><sup>th</sup> percentile is given by following steps</p>
<ol type="1">
<li><p>Find cumulative frequencies</p></li>
<li><p>Find <span class="math inline">\(\left( \frac{\text{x.n}}{100} \right)\)</span></p></li>
<li><p>See in the cumulative frequencies, the value just greater than<span class="math inline">\(\left( \frac{\text{x.n}}{100} \right)\)</span>and then the corresponding class interval is called <strong>Percentile class</strong>.</p></li>
<li><p>Use the following formula</p></li>
</ol>
<p><span class="math display">\[\mathbf{P}_{\mathbf{x}}\mathbf{= l +}\frac{\left( \frac{\mathbf{x \times n}}{\mathbf{100}} \right)\mathbf{- cf}}{\mathbf{f}}\mathbf{\times c}\]</span></p>
<p>Where</p>
<p><span class="math inline">\(\mathbf{l}\)</span> = lower limit of the percentile class</p>
<p><span class="math inline">\(\mathbf{\text{cf}}\)</span> = cumulative frequency preceding the percentile class</p>
<p><span class="math inline">\(\mathbf{f}\)</span> = frequency of the percentile class</p>
<p><span class="math inline">\(\mathbf{c}\)</span> = class interval</p>
<p><span class="math inline">\(\mathbf{n}\)</span> = total number of observations</p>
<p><strong>Example 5.9</strong>: Compute <span class="math inline">\(\mathbf{P}_{\mathbf{25}}\)</span><strong>and</strong> <span class="math inline">\(\mathbf{P}_{\mathbf{75}}\)</span> for the data 25, 18, 30, 8, 15, 5, 10, 35, 40, 45</p>
<p><strong>Solution 5.9</strong>:</p>
<p>First arrange the data in ascending order</p>
<p><strong>5, 8, 10, 15, 18, 25, 30, 35, 40, 45</strong></p>
<p>Here <em>n</em> =10</p>
<p><span class="math inline">\(\mathbf{P}_{\mathbf{25}}\mathbf{=}\left( \frac{\mathbf{25}\left( \mathbf{10 + 1} \right)}{\mathbf{100}} \right)^{\mathbf{\text{th}}}\)</span><strong>= 2.75<sup>th</sup> item</strong></p>
<p><span class="math inline">\(P_{25} =\)</span><!-- -->2.75<sup>th</sup> item = 2<sup>nd</sup> item + 0.75(3<sup>rd</sup> item – 2<sup>nd</sup> item)</p>
<p>So from the given data <span class="math inline">\(P_{25}\)</span>= 8+0.75(10– 8) = <strong>9.5</strong></p>
<p><span class="math inline">\(\mathbf{P}_{\mathbf{75}}\mathbf{=}\left( \frac{\mathbf{75}\left( \mathbf{10 + 1} \right)}{\mathbf{100}} \right)^{\mathbf{\text{th}}}\)</span><strong>= 8.25<sup>th</sup> item</strong></p>
<p><em>i</em>.<em>e</em>. <span class="math inline">\(P_{75} = \left( 75 \times \frac{10 + 1}{100} \right)^{th}\)</span> = 8.25<sup>th</sup> item = 8<sup>th</sup> item + 0.25(9<sup>th</sup> item –8<sup>th</sup> item) = 35+0.25(40-35) =36.25</p>
<div class="callout callout-style-default callout-important callout-titled" title="Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Data in Example 5.9 is same as Example 4.6; it can be seen that <span class="math inline">\(P_{25} = Q_{1}\)</span> &amp; <span class="math inline">\(P_{75} = Q_{3}\)</span> always</p>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try yourself
</div>
</div>
<div class="callout-body-container callout-body">
<p>Find <span class="math inline">\(\text{P}_{25}\)</span>, <span class="math inline">\(P_{50}\)</span>&amp; <span class="math inline">\(P_{75}\)</span> for Example <strong>5.7</strong> &amp; <strong>5.8</strong>; verify that <span class="math inline">\(P_{50} = Q_{2}\)</span>, <span class="math inline">\(P_{25} = Q_{1}\)</span> &amp; <span class="math inline">\(P_{75} = Q_{3}\)</span></p>
</div>
</div>
</section>
<section id="deciles" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="deciles"><span class="header-section-number">5.8</span> Deciles</h2>
<p>Deciles are similar to quartiles, but while quartiles consist of three points that divide an ordered dataset into four equal parts, deciles consist of 9 points that divide the dataset into ten equal parts. The <strong>x</strong><sup>th</sup> decile is denoted as <span class="math inline">\(d_x\)</span>. It is important to note that the <strong>median</strong> is the <strong>5th decile</strong>.</p>
<p><span class="math inline">\(\mathbf{d}_{\mathbf{x}}\mathbf{=}\left( \frac{\mathbf{x}\left( \mathbf{n + 1} \right)}{\mathbf{10}} \right)^{\mathbf{\text{th}}}\)</span><strong>item</strong></p>
<p>For a frequency distribution the <em>x</em><sup>th</sup> decile is given by following steps</p>
<ol type="1">
<li><p>Find cumulative frequencies</p></li>
<li><p>Find <span class="math inline">\(\left( \frac{\text{x.n}}{10} \right)\)</span></p></li>
<li><p>See in the cumulative frequencies, the value just greater than<span class="math inline">\(\left( \frac{\text{x.n}}{10} \right)\)</span>and then the corresponding class interval is called <strong>decile class</strong>.</p></li>
<li><p>Use the following formula</p></li>
</ol>
<p><span class="math display">\[\mathbf{d}_{\mathbf{x}}\mathbf{= l +}\frac{\left( \frac{\mathbf{x \times n}}{\mathbf{10}} \right)\mathbf{- cf}}{\mathbf{f}}\mathbf{\times c}\]</span></p>
<p>Where</p>
<p><span class="math inline">\(\mathbf{l}\)</span> = lower limit of the decile class</p>
<p><span class="math inline">\(\mathbf{\text{cf}}\)</span> = cumulative frequency preceding the decile class</p>
<p><span class="math inline">\(\mathbf{f}\)</span> = frequency of the decile class</p>
<p><span class="math inline">\(\mathbf{c}\)</span> = class interval</p>
<p><span class="math inline">\(\mathbf{n}\)</span> = total number of observations</p>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Try yourself
</div>
</div>
<div class="callout-body-container callout-body">
<p>Find <span class="math inline">\(\text{D}_{5}\)</span> for Example <strong>5.6</strong>, <strong>5.7</strong> &amp; <strong>5.8</strong>; verify that <span class="math inline">\(\text{D}_{5} = \text{Q}_{2} = \text{P}_{50} = median\)</span></p>
</div>
</div>
<p>&nbsp;<br>
&nbsp;<br>
&nbsp;</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Quotes to Inspire">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Quotes to Inspire
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>“The best thing about being a statistician is that you get to play in everybody else’s backyard”. – John Tukey</strong></p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/cleaning-data-r\.ala\.org\.au\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./central1.html" class="pagination-link" aria-label="Central tendency I">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Central tendency I</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./appendix1.html" class="pagination-link" aria-label="Appendix 1">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Appendix 1</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Published by PAPAYA publishing division of <a href="https://www.statoberry.com/papaya"><img src=".\images/statoberry.png" class="img-fluid" style="width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;"></a></p>
</div>   
    <div class="nav-footer-center">
<p><a href="https://www.statoberry.com/papaya"><img src=".\images/papayalogo.png" class="img-fluid" style="width: auto; height: 90px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;"></a></p>
</div>
    <div class="nav-footer-right">
<p>Licenced under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC-BY-NC-ND 4.0 Int License</a> <a href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img src=".\images/cclogo.png" class="img-fluid" style="width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;"></a> Built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>